name: build 

on: [push]
env:
  WF_ENV: Avaliable to all jobs

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Push a random file
        run: |
          pwd
          ls -a
          git init
          git remote add origin  "https://$GITHUB_ACTOR:${{ secrets.TOKEN_GITHUB }}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "my-example@example.com"
          git config --global user.name "my-example"
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull
          ls -a
          echo $RANDOM >> random.txt
          ls -a
          git add -A
          git commit -m"Random file"
          git push





      #   run: echo "Hello World"

      # - name: multiline script
      #   run: |
      #     node -v
      #     npm -v
          

